Chinese Translation Completion
Nomi-CEu/Nomi-CEu-Translations pull request #7
Opened 2024-01-06 13:23 UTC by zero6six

2024-01-07 07:24 UTC, IntegerLimit requested changes

2024-01-07 07:24 UTC, IntegerLimit commented on nomi-labs/assets/nomilabs/lang/zh_cn.lang
> +
Yep, all entries below this have been REMOVED, not missing. can you delete them please?

Thank you for doing this though, but just know that you can trust the english langs in this repository, they are auto-generated from the english langs in the original repository.

If you do feel like something might be missing, what you have done here is a great way of bringing that to our attention, but you could also ping me in the translations thread.

Apart from this, its all good.

2024-01-07 07:24 UTC, IntegerLimit commented on nomi-ceu/assets/contenttweaker/lang/zh_cn.lang
Also t6his file is not needed. Please delete it.

2024-01-07 07:26 UTC, IntegerLimit commented on nomi-ceu/assets/contenttweaker/lang/zh_cn.lang
Sorry, I did not realise that the english version was autogenerated by the nomi-ceu syncing. This is fine then.

2024-01-07 10:22 UTC, IntegerLimit requested changes
Can you also add the changes in https://github.com/Nomi-CEu/Nomi-CEu-Translations/commit/0c871386a376f93ae87b055dc06653cf8aaf37f2 first?

2024-01-07 15:08 UTC, zero6six commented on nomi-labs/assets/nomilabs/lang/zh_cn.lang
> +
Okay, I finished.

2024-01-07 15:12 UTC, zero6six commented
> Can you also add the changes in [0c87138](https://github.com/Nomi-CEu/Nomi-CEu-Translations/commit/0c871386a376f93ae87b055dc06653cf8aaf37f2) first?

Finished. But using `git rebase` seemed to cause a force push.

2024-01-07 15:19 UTC, zero6six commented
By the way, because of the final exam, I may not be online very often recently. I'm sorry about that.

2024-01-08 10:39 UTC, IntegerLimit approved these changes

2024-01-08 10:40 UTC, merged